name: crypted_preferences
description: Flutter preferences management with crypto capabilities
version: 0.0.3
homepage: https://github.com/jaumard/crypted_preferences
repository: https://github.com/jaumard/crypted_preferences
author: jaumard <jimmy.aumard@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.8
